name: application_paper
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dio: 3.0.8
  path_provider: ^1.6.0



dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - assets/images/image01.png
    - assets/images/1470137290773494.gif
    - assets/data/userInformation.json

